### DISCUSSION TITLE
Updated to v2, what thermal_perception changed for?

### DISCUSSION THREAD

**Discussion by SergioRius** [dolezsa/thermal_comfort#284] [Q&A] [answered]
Just updated to version 2 and my Home Assistant installation is complaining about not being able to start the thermal comfort integration because the configuration includes an entity "thermal_confort" that is invalid.

```yaml
      - name: thermal_comfort_lowerbathroom
        unique_id: thermal_comfort_lowerbathroom
        poll: true
        temperature_sensor: sensor.ble_lowerbathroom_temperature
        humidity_sensor: sensor.ble_lowerbathroom_humidity
        sensor_types:
          - heat_index
          - thermal_perception
          - absolute_humidity
          - dew_point
          - simmer_zone
```

Could anyone tell me what that sensor changed for, or where I can find a v1 to v2 migration document?
Thanks.
