### ISSUE TITLE
1.4 polling doesn't seem to work

### ISSUE THREAD

**Issue by lymanepp** [dolezsa/thermal_comfort#118]
I have polling enabled using this configuration, but it doesn't appear to do anything.

```
    - name: Guest Bath
      temperature_sensor: sensor.guest_bath_temperature
      humidity_sensor: sensor.guest_bath_humidity
      unique_id: guest_bath
      poll: true
      sensor_types:
        - absolute_humidity
        - dew_point
        - simmer_index
```

The spike happen when the first update is received. I have confirmed that the comfort sensors are updated at the same second as the underlying sensors are updated.

![image](https://user-images.githubusercontent.com/4195527/151862238-aab2c0f7-33e1-49e2-a448-2c79ad22d2d8.png)
