### ISSUE TITLE
Configure multiple sensors in UI

### ISSUE THREAD

**Issue by lukepighetti** [dolezsa/thermal_comfort#169]
I only see a way to make a single thermal comfort sensor. I'd like to make multiple. The concept is that if absolute humidity is lower outside than it is inside, we should pull air into the home from the outside.

Is there any way to do that? I don't see it.

**Comment by lukepighetti** [comment]
It looks like you can achieve this in `configuration.yaml` as so:

```yaml
thermal_comfort:
  sensor:
    - name: Indoor Thermal Comfort
      temperature_sensor: sensor.indoor_temperature_mean
      humidity_sensor: sensor.indoor_humidity_mean
    - name: Kitchen Thermal Comfort
      temperature_sensor: sensor.0x00158d0008027368_temperature
      humidity_sensor: sensor.0x00158d0008027368_humidity
    - name: Bedroom Thermal Comfort
      temperature_sensor: sensor.0x00158d000804a462_temperature
      humidity_sensor: sensor.0x00158d000804a462_humidity
```

But now I don't see a way to delete the single sensor you can create in the UI

<img width="571" alt="Screen Shot 2022-06-12 at 2 49 11 PM" src="https://user-images.githubusercontent.com/666539/173248681-e58dbf26-ff46-49d9-a360-3fc28c6a2f0d.png">
