### ISSUE TITLE
Feature: Support Weather Entity as input

### ISSUE THREAD

**Issue by rautesamtr** [dolezsa/thermal_comfort#231]

**Comment by Torgrima** [comment]
Weather sensor, as an outside temperature [Weather](https://www.home-assistant.io/integrations/#weather) 

I am not sure if met is still the default weather sensor in home-assistant: https://www.home-assistant.io/integrations/met/

But it has all the nessesary attribute like: temperature, humidity, pressure, wind_speed.
Met integration gives wether data for any location. 

An additional reason for supporing external Weather data is to be able to merge with the mold sensor in home-assistant. 

A sugestion if you one day will support picking attributes. 
Both Weather and climate have temperature as attributes. 

Thanks for an incredable project, thermal comfort adds a good value to home-assistant.

**Comment by bensebborn** [comment]
This would be handy. Otherwise we have to buy another sensor when the data is already there.

**Comment by jds11111** [comment]
Yes, that would be a natural thing to add, it is not a deal breaker, since one can create a temperature (or humidity) sensor from them with yaml.  For those reading this issue and not aware, here is an example.
```
sensor:
  - platform: template
    met_temperature:
      friendly_name: MET temperature
      unit_of_measurement: "°F"
      value_template: >
        {% if states('weather.home')  != 'unknown' and states('weather.home')  != 'Unavailable' %}
          {%if state_attr('weather.home','temperature') %}
            {{ state_attr('weather.home','temperature') }}
          {%endif %}
        {% else %}
          {{ states('sensor.met_temperature') }}
        {%endif %}
      device_class: temperature
```
On the other hand, if the weather bit is added to this great integration, then forecasts of those quantities would be available.

**Comment by ostracizado** [comment]
Are templates working?

```
#Outside Temperature
  - platform: template
    sensors:
      ipma_temperature:
        friendly_name: "Outside Temperature"
        unit_of_measurement: 'ºC'
        value_template: "{{ state_attr('weather.home', 'temperature') }}"
        
#Outside Humidity
  - platform: template
    sensors:
      ipma_humidity:
        friendly_name: "Outside Humidity"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.home', 'humidity') }}"
```

Even when I get the values in development tools, they are still unknown in thermal confort.
