### ISSUE TITLE
Dutch translation is incomplete

### ISSUE THREAD

**Issue by BebeMischa** [dolezsa/thermal_comfort#248]
Thanks for all the work on the integration.

Today I have updated to 2.0.1.

As I use the YAML way, I had to change a lot of my code, but got it working fine.

Only problem I see is, that `humidex_perception` does not translate on dashboard. My HA language is Dutch, but the sensor shows up in English. I see here on github, that a Dutch translation is present.

Previous version worked fine.

This is my configuration.yaml:

```yaml
#Thermal comfort
thermal_comfort:
  - custom_icons: true # global option for the entry
    sensor:
      - name: woonkamerdauw
        unique_id: woonkamerdauw1
        temperature_sensor: sensor.fibaro_eye_woon_air_temperature
        humidity_sensor: sensor.humidity
        sensor_types:
          - dew_point
          - humidex_perception
      - name: slaapkamerdauw
        unique_id: slaapkamerdauw1
        temperature_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_air_temperature
        humidity_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_humidity
        sensor_types:
          - humidex_perception
      - name: terrasdauw
        unique_id: terrasdauw1
        temperature_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_air_temperature_2
        humidity_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_humidity_2
        sensor_types:
          - humidex_perception
      - name: baddauw1
        unique_id: baddauw
        temperature_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_air_temperature_4
        humidity_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_humidity_4
        sensor_types:
          - humidex_perception
      - name: keukendauw
        unique_id: keukendauw1
        temperature_sensor: sensor.fibaro_eye_keukentafel_air_temperature
        humidity_sensor: sensor.humidity
        sensor_types:
          - humidex_perception
      - name: simcavedauw
        unique_id: simcavedauw1
        temperature_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_air_temperature_3
        humidity_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_humidity_3
        sensor_types:
          - humidex_perception
      - name: opslagdauw
        unique_id: opslagdaw1
        temperature_sensor: sensor.aeotec_humitemp_opslag_air_temperature
        humidity_sensor: sensor.aeotec_humitemp_opslag_humidity
        sensor_types:
          - humidex_perception
      - name: schuurdauw
        unique_id: schuurdauw1
        temperature_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_air_temperature_5
        humidity_sensor: sensor.aerq_temperature_and_humidity_sensor_v2_0_humidity_5
        sensor_types:
          - humidex_perception
```

Should I change something more or there is some bug?

Thank you very much in advance

Mischa

PS sorry, but whatever I do, the code won't display correctly...
