### ISSUE TITLE
Internationalization doesn't work with `custom:multiple-entity-row` anymore

### ISSUE THREAD

**Issue by nikipore** [dolezsa/thermal_comfort#261]
With the very useful custom card "multiple entity row", the internationalization is broken. It used to work properly until recently and broke with one of the last Thermal Comfort releases.

```yaml
entities:
  - entity: sensor.wohnzimmer_summer_simmer_perception
    type: custom:multiple-entity-row
    name: Wärme
    entities:
      - entity: binary_sensor.wohnzimmer_ventilate_temperature
        name: false
        hide_if: 'off'
        state_color: true
        icon: true
  - entity: sensor.wohnzimmer_dew_point_perception
    type: custom:multiple-entity-row
    name: Klima
    entities:
      - entity: binary_sensor.wohnzimmer_ventilate_humidity
        name: false
        hide_if: 'off'
        state_color: true
        icon: true
```

This combines a summer simmer (dew point) perception with a ventilation recommendation when it is colder (less humid) outside:
![Bildschirm­foto 2023-01-14 um 18 41 41](https://user-images.githubusercontent.com/640781/212487433-88526fc3-fa6a-4216-bc7b-bc41a6059d3b.png)

The internationalization of the sensor itself it still working correctly:
![Bildschirm­foto 2023-01-14 um 18 42 04](https://user-images.githubusercontent.com/640781/212487434-6195b3ab-9bb7-49c5-8d49-8765e18d70e8.png)
