### ISSUE TITLE
Thermal Comfort - [poll] is an invalid option

### ISSUE THREAD

**Issue by Gordan74** [dolezsa/thermal_comfort#89]
Hello,
I updated Thermal Comfort through HACS to 1.2.2.
I have also updated HA to 2021.12.9.
Now I get following when checking configuration:
_Invalid config for [sensor.thermal_comfort]: [poll] is an invalid option for [sensor.thermal_comfort]. Check: sensor.thermal_comfort->poll. (See ?, line ?)._ 

In config I have following:
```yaml
  - platform: thermal_comfort
    poll: true
    scan_interval: 300
    sensors:
      dnevni_boravak:
        friendly_name: Dnevni boravak
        temperature_sensor: sensor.temperatura_dnevni_boravak
        humidity_sensor: sensor.vlaga_dnevni_boravak
```
This used to work previously.. :)
Thanks for your help.
Best regards,
Gordan
